name: GitHub Actions Demo
run-name: ${{ github.actor }} is running the tests
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the zig compiler
        uses: mlugg/setup-zig@v1
      - name: Run the tests
        run: |
          zig build test --summary all
      - run: echo "🍏 Job done. Exited with status ${{ job.status }}."
